Search.appendIndex(
    [
                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand",
            "name": "EntityFinderCommand",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003Aconfigure\u0028\u0029",
            "name": "configure",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_configure"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003Aexecute\u0028\u0029",
            "name": "execute",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_execute"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003Aloop\u0028\u0029",
            "name": "loop",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_loop"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003Aoutput\u0028\u0029",
            "name": "output",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_output"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003AfindEntity\u0028\u0029",
            "name": "findEntity",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_findEntity"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003AcreateText\u0028\u0029",
            "name": "createText",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_createText"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003ArunExtendEntityFinderEvent\u0028\u0029",
            "name": "runExtendEntityFinderEvent",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_runExtendEntityFinderEvent"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003AfindFrontendModuleParents\u0028\u0029",
            "name": "findFrontendModuleParents",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_findFrontendModuleParents"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003AfindInserttags\u0028\u0029",
            "name": "findInserttags",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#method_findInserttags"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024defaultName",
            "name": "defaultName",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_defaultName"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024defaultDescription",
            "name": "defaultDescription",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_defaultDescription"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024eventDispatcher",
            "name": "eventDispatcher",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_eventDispatcher"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024connection",
            "name": "connection",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_connection"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command\\EntityFinderCommand\u003A\u003A\u0024entityFinderHelper",
            "name": "entityFinderHelper",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Command-EntityFinderCommand.html#property_entityFinderHelper"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\ContaoManager\\Plugin",
            "name": "Plugin",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-ContaoManager-Plugin.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\ContaoManager\\Plugin\u003A\u003AgetBundles\u0028\u0029",
            "name": "getBundles",
            "summary": "\u007B\u0040inheritdoc\u007D",
            "url": "classes/HeimrichHannot-UtilsBundle-ContaoManager-Plugin.html#method_getBundles"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\ContaoManager\\Plugin\u003A\u003AregisterContainerConfiguration\u0028\u0029",
            "name": "registerContainerConfiguration",
            "summary": "Allows\u0020a\u0020plugin\u0020to\u0020load\u0020container\u0020configuration.",
            "url": "classes/HeimrichHannot-UtilsBundle-ContaoManager-Plugin.html#method_registerContainerConfiguration"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField",
            "name": "AuthorField",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020a\u0020dca\u0020to\u0020have\u0020an\u0020author\u0020field\u0020and\u0020update\u0020logic\u0020added.",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html#method_register"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField\u003A\u003AgetRegistrations\u0028\u0029",
            "name": "getRegistrations",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html#method_getRegistrations"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField\u003A\u003ATYPE_USER",
            "name": "TYPE_USER",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html#constant_TYPE_USER"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField\u003A\u003ATYPE_MEMBER",
            "name": "TYPE_MEMBER",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html#constant_TYPE_MEMBER"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorField\u003A\u003A\u0024tables",
            "name": "tables",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorField.html#property_tables"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions",
            "name": "AuthorFieldOptions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_getTable"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AgetType\u0028\u0029",
            "name": "getType",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_getType"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetType\u0028\u0029",
            "name": "setType",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setType"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AhasFieldNamePrefix\u0028\u0029",
            "name": "hasFieldNamePrefix",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_hasFieldNamePrefix"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AgetFieldNamePrefix\u0028\u0029",
            "name": "getFieldNamePrefix",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_getFieldNamePrefix"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetFieldNamePrefix\u0028\u0029",
            "name": "setFieldNamePrefix",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setFieldNamePrefix"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AisUseDefaultLabel\u0028\u0029",
            "name": "isUseDefaultLabel",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_isUseDefaultLabel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetUseDefaultLabel\u0028\u0029",
            "name": "setUseDefaultLabel",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setUseDefaultLabel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AisExclude\u0028\u0029",
            "name": "isExclude",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_isExclude"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetExclude\u0028\u0029",
            "name": "setExclude",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setExclude"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AisSearch\u0028\u0029",
            "name": "isSearch",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_isSearch"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetSearch\u0028\u0029",
            "name": "setSearch",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setSearch"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AisFilter\u0028\u0029",
            "name": "isFilter",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_isFilter"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003AsetFilter\u0028\u0029",
            "name": "setFilter",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#method_setFilter"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_table"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024type",
            "name": "type",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_type"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024fieldNamePrefix",
            "name": "fieldNamePrefix",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_fieldNamePrefix"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024useDefaultLabel",
            "name": "useDefaultLabel",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_useDefaultLabel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024exclude",
            "name": "exclude",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_exclude"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024search",
            "name": "search",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_search"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca\\AuthorFieldOptions\u003A\u003A\u0024filter",
            "name": "filter",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dca-AuthorFieldOptions.html#property_filter"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator",
            "name": "DOMLettersIterator",
            "summary": "Iterates\u0020individual\u0020characters\u0020\u0028Unicode\u0020codepoints\u0029\u0020of\u0020DOM\u0020text\u0020and\u0020CDATA\u0020nodes\nwhile\u0020keeping\u0020track\u0020of\u0020their\u0020position\u0020in\u0020the\u0020document.",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "expects\u0020DOMElement\u0020or\u0020DOMDocument\u0020\u0028see\u0020DOMDocument\u003A\u003Aload\u0020and\u0020DOMDocument\u003A\u003AloadHTML\u0029.",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003AcurrentTextPosition\u0028\u0029",
            "name": "currentTextPosition",
            "summary": "Returns\u0020position\u0020in\u0020text\u0020as\u0020DOMText\u0020node\u0020and\u0020character\u0020offset.",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_currentTextPosition"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003AcurrentElement\u0028\u0029",
            "name": "currentElement",
            "summary": "Returns\u0020DOMElement\u0020that\u0020is\u0020currently\u0020being\u0020iterated\u0020or\u0020NULL\u0020if\u0020iterator\u0020has\u0020finished.",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_currentElement"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024key",
            "name": "key",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_key"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003Anext\u0028\u0029",
            "name": "next",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_next"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024current",
            "name": "current",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_current"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003Avalid\u0028\u0029",
            "name": "valid",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_valid"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003Arewind\u0028\u0029",
            "name": "rewind",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_rewind"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003AisTextNode\u0028\u0029",
            "name": "isTextNode",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_isTextNode"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003AaddToQueue\u0028\u0029",
            "name": "addToQueue",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#method_addToQueue"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024start",
            "name": "start",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_start"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024offset",
            "name": "offset",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_offset"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024letters",
            "name": "letters",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_letters"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom\\DOMLettersIterator\u003A\u003A\u0024queue",
            "name": "queue",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Dom-DOMLettersIterator.html#property_queue"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder\\EntityFinderHelper",
            "name": "EntityFinderHelper",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EntityFinder-EntityFinderHelper.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder\\EntityFinderHelper\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EntityFinder-EntityFinderHelper.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder\\EntityFinderHelper\u003A\u003AfindModulesByTypeAndSerializedValue\u0028\u0029",
            "name": "findModulesByTypeAndSerializedValue",
            "summary": "Search\u0020within\u0020serialized\u0020array\u0020fields\u0020of\u0020the\u0020model\u0020entity.",
            "url": "classes/HeimrichHannot-UtilsBundle-EntityFinder-EntityFinderHelper.html#method_findModulesByTypeAndSerializedValue"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder\\EntityFinderHelper\u003A\u003A\u0024utils",
            "name": "utils",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EntityFinder-EntityFinderHelper.html#property_utils"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder\\EntityFinderHelper\u003A\u003A\u0024framework",
            "name": "framework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EntityFinder-EntityFinderHelper.html#property_framework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent",
            "name": "ExtendEntityFinderEvent",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetTable\u0028\u0029",
            "name": "getTable",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getTable"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetId\u0028\u0029",
            "name": "getId",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getId"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AaddParent\u0028\u0029",
            "name": "addParent",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_addParent"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetParents\u0028\u0029",
            "name": "getParents",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getParents"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AsetParents\u0028\u0029",
            "name": "setParents",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_setParents"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetOutput\u0028\u0029",
            "name": "getOutput",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getOutput"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AsetOutput\u0028\u0029",
            "name": "setOutput",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_setOutput"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AisOnlyText\u0028\u0029",
            "name": "isOnlyText",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_isOnlyText"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AaddInserttag\u0028\u0029",
            "name": "addInserttag",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_addInserttag"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetInserttags\u0028\u0029",
            "name": "getInserttags",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getInserttags"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AsetInserttags\u0028\u0029",
            "name": "setInserttags",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_setInserttags"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003AgetEntityFinderHelper\u0028\u0029",
            "name": "getEntityFinderHelper",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#method_getEntityFinderHelper"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024output",
            "name": "output",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_output"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_table"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024id",
            "name": "id",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_id"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024parents",
            "name": "parents",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_parents"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024inserttags",
            "name": "inserttags",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_inserttags"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024entityFinderHelper",
            "name": "entityFinderHelper",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_entityFinderHelper"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event\\ExtendEntityFinderEvent\u003A\u003A\u0024onlyText",
            "name": "onlyText",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Event-ExtendEntityFinderEvent.html#property_onlyText"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener",
            "name": "DcaAuthorListener",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003AonLoadDataContainer\u0028\u0029",
            "name": "onLoadDataContainer",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#method_onLoadDataContainer"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003AonConfigCopyCallback\u0028\u0029",
            "name": "onConfigCopyCallback",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#method_onConfigCopyCallback"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003AgetAuthorFieldName\u0028\u0029",
            "name": "getAuthorFieldName",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#method_getAuthorFieldName"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003A\u0024framework",
            "name": "framework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#property_framework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\DcaAuthorListener\u003A\u003A\u0024security",
            "name": "security",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-DcaAuthorListener.html#property_security"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\ExtendEntityFinderSubscriber",
            "name": "ExtendEntityFinderSubscriber",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-ExtendEntityFinderSubscriber.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\ExtendEntityFinderSubscriber\u003A\u003AgetSubscribedEvents\u0028\u0029",
            "name": "getSubscribedEvents",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-ExtendEntityFinderSubscriber.html#method_getSubscribedEvents"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\ExtendEntityFinderSubscriber\u003A\u003AonExtendEntityFinderEvent\u0028\u0029",
            "name": "onExtendEntityFinderEvent",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-ExtendEntityFinderSubscriber.html#method_onExtendEntityFinderEvent"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\ExtendEntityFinderSubscriber\u003A\u003AfindNewsEntity\u0028\u0029",
            "name": "findNewsEntity",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-ExtendEntityFinderSubscriber.html#method_findNewsEntity"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener\\ExtendEntityFinderSubscriber\u003A\u003AfindBlockElements\u0028\u0029",
            "name": "findBlockElements",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-EventListener-ExtendEntityFinderSubscriber.html#method_findBlockElements"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Exception\\InvalidUrlException",
            "name": "InvalidUrlException",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Exception-InvalidUrlException.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Exception\\InvalidUrlException\u003A\u003A\u0024message",
            "name": "message",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Exception-InvalidUrlException.html#property_message"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\HeimrichHannotUtilsBundle",
            "name": "HeimrichHannotUtilsBundle",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-HeimrichHannotUtilsBundle.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\HeimrichHannotUtilsBundle\u003A\u003AgetPath\u0028\u0029",
            "name": "getPath",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-HeimrichHannotUtilsBundle.html#method_getPath"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig\\StringExtension",
            "name": "StringExtension",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Twig-StringExtension.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig\\StringExtension\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Twig-StringExtension.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig\\StringExtension\u003A\u003AgetFilters\u0028\u0029",
            "name": "getFilters",
            "summary": "Get\u0020list\u0020of\u0020twig\u0020filters.",
            "url": "classes/HeimrichHannot-UtilsBundle-Twig-StringExtension.html#method_getFilters"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig\\StringExtension\u003A\u003AanonymizeEmail\u0028\u0029",
            "name": "anonymizeEmail",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Twig-StringExtension.html#method_anonymizeEmail"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig\\StringExtension\u003A\u003A\u0024utils",
            "name": "utils",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Twig-StringExtension.html#property_utils"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AbstractServiceSubscriber",
            "name": "AbstractServiceSubscriber",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AbstractServiceSubscriber.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil",
            "name": "AccordionUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003AstructureAccordionStartStop\u0028\u0029",
            "name": "structureAccordionStartStop",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#method_structureAccordionStartStop"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003AstructureAccordionSingle\u0028\u0029",
            "name": "structureAccordionSingle",
            "summary": "Adds\u0020the\u0020following\u0020flags\u0020to\u0020the\u0020template\u0020data\u003A\n\u002D\u0020first\n\u002D\u0020last\n\u002D\u0020parentId.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#method_structureAccordionSingle"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003AgenerateAccordionLevel\u0028\u0029",
            "name": "generateAccordionLevel",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#method_generateAccordionLevel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003A\u0024accordionStartStopCache",
            "name": "accordionStartStopCache",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#property_accordionStartStopCache"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003A\u0024accordionSingleCache",
            "name": "accordionSingleCache",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#property_accordionSingleCache"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AccordionUtil\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AccordionUtil.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AnonymizeUtil",
            "name": "AnonymizeUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AnonymizeUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\AnonymizeUtil\u003A\u003AanonymizeEmail\u0028\u0029",
            "name": "anonymizeEmail",
            "summary": "Returns\u0020an\u0020anonymized\u0020email\u0020address.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-AnonymizeUtil.html#method_anonymizeEmail"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ArrayUtil",
            "name": "ArrayUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ArrayUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ArrayUtil\u003A\u003AinsertBeforeKey\u0028\u0029",
            "name": "insertBeforeKey",
            "summary": "Insert\u0020a\u0020new\u0020entry\u0020before\u0020a\u0020specific\u0020or\u0020multiple\u0020keys\u0020in\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ArrayUtil.html#method_insertBeforeKey"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ArrayUtil\u003A\u003AinsertAfterKey\u0028\u0029",
            "name": "insertAfterKey",
            "summary": "Insert\u0020a\u0020value\u0020into\u0020an\u0020existing\u0020array\u0020by\u0020key\u0020name.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ArrayUtil.html#method_insertAfterKey"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ArrayUtil\u003A\u003AremoveValue\u0028\u0029",
            "name": "removeValue",
            "summary": "Removes\u0020a\u0020value\u0020in\u0020an\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ArrayUtil.html#method_removeValue"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil",
            "name": "ContainerUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisBackend\u0028\u0029",
            "name": "isBackend",
            "summary": "Return\u0020if\u0020currently\u0020in\u0020backend\u0020scope.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isBackend"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisFrontend\u0028\u0029",
            "name": "isFrontend",
            "summary": "Return\u0020if\u0020currently\u0020in\u0020frontend\u0020scope.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isFrontend"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisFrontendCron\u0028\u0029",
            "name": "isFrontendCron",
            "summary": "Return\u0020if\u0020in\u0020cron\u0020route\u0020\u0028Attention\u003A\u0020not\u0020cron\u0020command\u0021\u0029.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isFrontendCron"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisInstall\u0028\u0029",
            "name": "isInstall",
            "summary": "Return\u0020if\u0020in\u0020install\u0020route\u0020\u0028Attention\u003A\u0020not\u0020migration\u0021\u0029.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isInstall"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisDev\u0028\u0029",
            "name": "isDev",
            "summary": "Return\u0020if\u0020in\u0020dev\u0020environment.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isDev"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003Alog\u0028\u0029",
            "name": "log",
            "summary": "Add\u0020a\u0020log\u0020entry\u0020to\u0020contao\u0020system\u0020log.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_log"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AgetBundlePath\u0028\u0029",
            "name": "getBundlePath",
            "summary": "Returns\u0020the\u0020path\u0020to\u0020the\u0020bundle\u0020in\u0020vendor\u0020folder\nAttention\u003A\u0020resolves\u0020symlinks\u0021",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_getBundlePath"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AgetBundleResourcePath\u0028\u0029",
            "name": "getBundleResourcePath",
            "summary": "Returns\u0020the\u0020path\u0020or\u0020paths\u0020to\u0020a\u0020ressource\u0020within\u0020a\u0020bundle\nAttention\u003A\u0020resolves\u0020symlinks\u0021",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_getBundleResourcePath"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisMaintenanceModeActive\u0028\u0029",
            "name": "isMaintenanceModeActive",
            "summary": "Return\u0020if\u0020currently\u0020in\u0020maintenance\u0020mode.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isMaintenanceModeActive"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AisPreviewMode\u0028\u0029",
            "name": "isPreviewMode",
            "summary": "Return\u0020if\u0020currently\u0020in\u0020preview\u0020mode.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_isPreviewMode"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003AgetSubscribedServices\u0028\u0029",
            "name": "getSubscribedServices",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#method_getSubscribedServices"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024locator",
            "name": "locator",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_locator"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024kernel",
            "name": "kernel",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_kernel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024framework",
            "name": "framework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_framework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024scopeMatcher",
            "name": "scopeMatcher",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_scopeMatcher"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024requestStack",
            "name": "requestStack",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_requestStack"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ContainerUtil\u003A\u003A\u0024filesystem",
            "name": "filesystem",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ContainerUtil.html#property_filesystem"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DatabaseUtil",
            "name": "DatabaseUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DatabaseUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DatabaseUtil\u003A\u003AcreateWhereForSerializedBlob\u0028\u0029",
            "name": "createWhereForSerializedBlob",
            "summary": "Create\u0020a\u0020where\u0020condition\u0020for\u0020a\u0020field\u0020that\u0020contains\u0020a\u0020serialized\u0020blob.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DatabaseUtil.html#method_createWhereForSerializedBlob"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions",
            "name": "GetDcaFieldsOptions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AisOnlyDatabaseFields\u0028\u0029",
            "name": "isOnlyDatabaseFields",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_isOnlyDatabaseFields"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_create"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AsetOnlyDatabaseFields\u0028\u0029",
            "name": "setOnlyDatabaseFields",
            "summary": "Return\u0020only\u0020fields\u0020with\u0020sql\u0020definition.\u0020Default\u0020false",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_setOnlyDatabaseFields"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AgetAllowedInputTypes\u0028\u0029",
            "name": "getAllowedInputTypes",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_getAllowedInputTypes"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AsetAllowedInputTypes\u0028\u0029",
            "name": "setAllowedInputTypes",
            "summary": "Return\u0020only\u0020fields\u0020of\u0020given\u0020types.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_setAllowedInputTypes"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AisOnlyAllowedInputTypes\u0028\u0029",
            "name": "isOnlyAllowedInputTypes",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_isOnlyAllowedInputTypes"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AgetEvalConditions\u0028\u0029",
            "name": "getEvalConditions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_getEvalConditions"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AsetEvalConditions\u0028\u0029",
            "name": "setEvalConditions",
            "summary": "Return\u0020only\u0020fields\u0020with\u0020given\u0020eval\u0020key\u002Dvalue\u002Dpairs.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_setEvalConditions"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AisHasEvalConditions\u0028\u0029",
            "name": "isHasEvalConditions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_isHasEvalConditions"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AisLocalizeLabels\u0028\u0029",
            "name": "isLocalizeLabels",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_isLocalizeLabels"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AsetLocalizeLabels\u0028\u0029",
            "name": "setLocalizeLabels",
            "summary": "Return\u0020also\u0020the\u0020field\u0020labels\u0020\u0028key\u0020\u003D\u0020field\u0020name,\u0020value\u0020\u003D\u0020field\u0020label\u0029.\u0020Default\u0020false",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_setLocalizeLabels"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AisSkipSorting\u0028\u0029",
            "name": "isSkipSorting",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_isSkipSorting"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003AsetSkipSorting\u0028\u0029",
            "name": "setSkipSorting",
            "summary": "Skip\u0020sorting\u0020fields\u0020by\u0020field\u0020name\u0020alphabetical.\u0020Default\u0020false",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#method_setSkipSorting"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003A\u0024onlyDatabaseFields",
            "name": "onlyDatabaseFields",
            "summary": "\u0027onlyDatabaseFields\u0027\u0020\u003D\u003E\u0020false,\n\u0027allowedInputTypes\u0027\u0020\u003D\u003E\u0020\u005B\u005D,\n\u0027evalConditions\u0027\u0020\u003D\u003E\u0020\u005B\u005D,\n\u0027localizeLabels\u0027\u0020\u003D\u003E\u0020false,\n\u0027skipSorting\u0027\u0020\u003D\u003E\u0020false,",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#property_onlyDatabaseFields"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003A\u0024allowedInputTypes",
            "name": "allowedInputTypes",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#property_allowedInputTypes"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003A\u0024evalConditions",
            "name": "evalConditions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#property_evalConditions"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003A\u0024localizeLabels",
            "name": "localizeLabels",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#property_localizeLabels"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\\GetDcaFieldsOptions\u003A\u003A\u0024skipSorting",
            "name": "skipSorting",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil-GetDcaFieldsOptions.html#property_skipSorting"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil",
            "name": "DcaUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\u003A\u003AgetPaletteFields\u0028\u0029",
            "name": "getPaletteFields",
            "summary": "Return\u0020all\u0020fields\u0020of\u0020a\u0020palette\u0020including\u0020its\u0020subpalettes\u0020as\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html#method_getPaletteFields"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\u003A\u003AexplodePalette\u0028\u0029",
            "name": "explodePalette",
            "summary": "Explode\u0020a\u0020palette\u0020string.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html#method_explodePalette"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\u003A\u003AgetDcaFields\u0028\u0029",
            "name": "getDcaFields",
            "summary": "Return\u0020a\u0020list\u0020of\u0020dca\u0020fields\u0020for\u0020given\u0020table.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html#method_getDcaFields"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-DcaUtil.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\FileUtil",
            "name": "FileUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-FileUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\FileUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-FileUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\FileUtil\u003A\u003AgetPathFromUuid\u0028\u0029",
            "name": "getPathFromUuid",
            "summary": "Get\u0020the\u0020path\u0020from\u0020a\u0020uuid.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-FileUtil.html#method_getPathFromUuid"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\FileUtil\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-FileUtil.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\FileUtil\u003A\u003A\u0024projectDir",
            "name": "projectDir",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-FileUtil.html#property_projectDir"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions",
            "name": "GenerateDataAttributesStringOptions",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003Acreate\u0028\u0029",
            "name": "create",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_create"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AisXhtml\u0028\u0029",
            "name": "isXhtml",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_isXhtml"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AsetXhtml\u0028\u0029",
            "name": "setXhtml",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_setXhtml"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AisNormalizeKeys\u0028\u0029",
            "name": "isNormalizeKeys",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_isNormalizeKeys"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AsetNormalizeKeys\u0028\u0029",
            "name": "setNormalizeKeys",
            "summary": "Array\u0020keys\u0020are\u0020normalized\u0020to\u0020lowercase\u0020dash\u002Dcased\u0020strings\u0020\u0028e.g.\u0020Foo\u0020Bar_player\u0020is\u0020transformed\u0020to\u0020foo\u002Dbar\u002Dplayer\u0029",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_setNormalizeKeys"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AgetArrayHandling\u0028\u0029",
            "name": "getArrayHandling",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_getArrayHandling"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003AsetArrayHandling\u0028\u0029",
            "name": "setArrayHandling",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#method_setArrayHandling"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003A\u0024xhtml",
            "name": "xhtml",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#property_xhtml"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003A\u0024normalizeKeys",
            "name": "normalizeKeys",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#property_normalizeKeys"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\\GenerateDataAttributesStringOptions\u003A\u003A\u0024arrayHandling",
            "name": "arrayHandling",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil-GenerateDataAttributesStringOptions.html#property_arrayHandling"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil",
            "name": "HtmlUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\u003A\u003AgenerateAttributeString\u0028\u0029",
            "name": "generateAttributeString",
            "summary": "Generate\u0020a\u0020attribute\u0020string\u0020for\u0020html\u0020elements\u0020out\u0020of\u0020an\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil.html#method_generateAttributeString"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil\u003A\u003AgenerateDataAttributesString\u0028\u0029",
            "name": "generateDataAttributesString",
            "summary": "Generates\u0020a\u0020data\u002Dattributes\u0020string\u0020out\u0020of\u0020an\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-HtmlUtil.html#method_generateDataAttributesString"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\LocaleUtil",
            "name": "LocaleUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-LocaleUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\LocaleUtil\u003A\u003AensureLineBreaks\u0028\u0029",
            "name": "ensureLineBreaks",
            "summary": "Ensure\u0020language\u0020specific\u0020line\u0020breaks.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-LocaleUtil.html#method_ensureLineBreaks"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil",
            "name": "ModelUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AaddPublishedCheckToModelArrays\u0028\u0029",
            "name": "addPublishedCheckToModelArrays",
            "summary": "Adds\u0020an\u0020published\u0020check\u0020to\u0020your\u0020model\u0020query.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_addPublishedCheckToModelArrays"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindModelInstancesBy\u0028\u0029",
            "name": "findModelInstancesBy",
            "summary": "Returns\u0020model\u0020instances\u0020by\u0020given\u0020table\u0020and\u0020search\u0020criteria.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findModelInstancesBy"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindModelInstanceByPk\u0028\u0029",
            "name": "findModelInstanceByPk",
            "summary": "Find\u0020a\u0020single\u0020model\u0020instance\u0020for\u0020given\u0020table\u0020by\u0020its\u0020primary\u0020key\u0020\u0028id\u0029.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findModelInstanceByPk"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindOneModelInstanceBy\u0028\u0029",
            "name": "findOneModelInstanceBy",
            "summary": "Return\u0020a\u0020single\u0020model\u0020instance\u0020by\u0020table\u0020and\u0020search\u0020criteria.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findOneModelInstanceBy"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindMultipleModelInstancesByIds\u0028\u0029",
            "name": "findMultipleModelInstancesByIds",
            "summary": "Returns\u0020multiple\u0020model\u0020instances\u0020by\u0020given\u0020table\u0020and\u0020ids.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findMultipleModelInstancesByIds"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindModelInstanceByIdOrAlias\u0028\u0029",
            "name": "findModelInstanceByIdOrAlias",
            "summary": "Returns\u0020model\u0020instance\u0020by\u0020given\u0020table\u0020and\u0020id\u0020or\u0020alias.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findModelInstanceByIdOrAlias"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003AfindParentsRecursively\u0028\u0029",
            "name": "findParentsRecursively",
            "summary": "Returns\u0020an\u0020array\u0020of\u0020a\u0020model\u0020instance\u0027s\u0020parents\u0020in\u0020ascending\u0020order,\u0020i.e.\u0020the\u0020root\u0020parent\u0020comes\u0020first.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#method_findParentsRecursively"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\ModelUtil\u003A\u003A\u0024framework",
            "name": "framework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-ModelUtil.html#property_framework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil",
            "name": "RequestUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003AgetCurrentPageModel\u0028\u0029",
            "name": "getCurrentPageModel",
            "summary": "Return\u0020the\u0020current\u0020page\u0020model.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method_getCurrentPageModel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003AgetCurrentRootPageModel\u0028\u0029",
            "name": "getCurrentRootPageModel",
            "summary": "Return\u0020the\u0020root\u0020page\u0020of\u0020the\u0020current\u0020page.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method_getCurrentRootPageModel"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003AgetBaseUrl\u0028\u0029",
            "name": "getBaseUrl",
            "summary": "Get\u0020the\u0020website\u0020base\u0020url\u0020\u0028scheme\u0020and\u0020host\u0029\u0020considering\u0020additional\u0020context.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method_getBaseUrl"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003AisIndexPage\u0028\u0029",
            "name": "isIndexPage",
            "summary": "Return\u0020true\u0020if\u0020the\u0020current\u0020page\u0020\u0028or\u0020the\u0020passed\u0020page\u0029\u0020is\u0020the\u0020index\/\u0020start\u0020page\nof\u0020the\u0020current\u0020page\u0020tree.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method_isIndexPage"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003AisNewVisitor\u0028\u0029",
            "name": "isNewVisitor",
            "summary": "Detect\u0020if\u0020user\u0020already\u0020visited\u0020our\u0020domain\u0020before.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#method_isNewVisitor"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003A\u0024requestStack",
            "name": "requestStack",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#property_requestStack"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RequestUtil\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RequestUtil.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil",
            "name": "RoutingUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003AgenerateBackendRoute\u0028\u0029",
            "name": "generateBackendRoute",
            "summary": "Generate\u0020a\u0020backend\u0020route\u0020with\u0020token\u0020and\u0020referer.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#method_generateBackendRoute"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003A\u0024tokenManager",
            "name": "tokenManager",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#property_tokenManager"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003A\u0024router",
            "name": "router",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#property_router"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003A\u0024csrfTokenName",
            "name": "csrfTokenName",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#property_csrfTokenName"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\RoutingUtil\u003A\u003A\u0024requestStack",
            "name": "requestStack",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-RoutingUtil.html#property_requestStack"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil",
            "name": "StringUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AcamelCaseToDashed\u0028\u0029",
            "name": "camelCaseToDashed",
            "summary": "Convert\u0020a\u0020camel\u0020case\u0020string\u0020to\u0020a\u0020dashed\u0020string.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_camelCaseToDashed"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AcamelCaseToSnake\u0028\u0029",
            "name": "camelCaseToSnake",
            "summary": "Convert\u0020a\u0020camel\u0020case\u0020string\u0020to\u0020a\u0020snake\u0020cased\u0020string.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_camelCaseToSnake"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ArandomChar\u0028\u0029",
            "name": "randomChar",
            "summary": "Return\u0020a\u0020random\u0020char.\u0020Can\u0020be\u0020a\u0020letter\u0020or\u0020a\u0020number.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_randomChar"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ArandomLetter\u0028\u0029",
            "name": "randomLetter",
            "summary": "Return\u0020a\u0020random\u0020letter\u0020char.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_randomLetter"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ArandomNumber\u0028\u0029",
            "name": "randomNumber",
            "summary": "Return\u0020a\u0020random\u0020number\u0020char.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_randomNumber"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003Arandom\u0028\u0029",
            "name": "random",
            "summary": "Return\u0020a\u0020random\u0020char\u0020of\u0020a\u0020given\u0020string.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_random"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AtruncateHtml\u0028\u0029",
            "name": "truncateHtml",
            "summary": "Truncates\u0020the\u0020text\u0020of\u0020a\u0020html\u0020string.\u0020By\u0020default,\u0020the\u0020last\u0020word\u0020is\u0020kept\u0020complete.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_truncateHtml"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ApregReplaceLast\u0028\u0029",
            "name": "pregReplaceLast",
            "summary": "Replace\u0020the\u0020last\u0020match\u0020of\u0020string\u0020with\u0020preg_replace.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_pregReplaceLast"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AconvertXmlToArray\u0028\u0029",
            "name": "convertXmlToArray",
            "summary": "Convert\u0020an\u0020xml\u0020string\u0020to\u0020array.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_convertXmlToArray"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AremoveLeadingString\u0028\u0029",
            "name": "removeLeadingString",
            "summary": "Remove\u0020a\u0020string\u0020from\u0020the\u0020beginning\u0020of\u0020\u0024subject.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_removeLeadingString"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003AremoveTrailingString\u0028\u0029",
            "name": "removeTrailingString",
            "summary": "Remove\u0020a\u0020string\u0020from\u0020the\u0020end\u0020of\u0020\u0024subject.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#method_removeTrailingString"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ACAPITAL_LETTERS",
            "name": "CAPITAL_LETTERS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_CAPITAL_LETTERS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ACAPITAL_LETTERS_NONAMBIGUOUS",
            "name": "CAPITAL_LETTERS_NONAMBIGUOUS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_CAPITAL_LETTERS_NONAMBIGUOUS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ASMALL_LETTERS",
            "name": "SMALL_LETTERS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_SMALL_LETTERS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ASMALL_LETTERS_NONAMBIGUOUS",
            "name": "SMALL_LETTERS_NONAMBIGUOUS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_SMALL_LETTERS_NONAMBIGUOUS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ANUMBERS",
            "name": "NUMBERS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_NUMBERS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\StringUtil\u003A\u003ANUMBERS_NONAMBIGUOUS",
            "name": "NUMBERS_NONAMBIGUOUS",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-StringUtil.html#constant_NUMBERS_NONAMBIGUOUS"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil",
            "name": "UrlUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003AremoveQueryStringParameterFromUrl\u0028\u0029",
            "name": "removeQueryStringParameterFromUrl",
            "summary": "Remove\u0020a\u0020query\u0020parameter\u0020\u0028GET\u0020parameter\u0029\u0020from\u0020an\u0020url.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#method_removeQueryStringParameterFromUrl"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003AaddQueryStringParameterToUrl\u0028\u0029",
            "name": "addQueryStringParameterToUrl",
            "summary": "Add\u0020a\u0020query\u0020string\u0020parameter\u0020to\u0020an\u0020url.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#method_addQueryStringParameterToUrl"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003AmakeUrlRelative\u0028\u0029",
            "name": "makeUrlRelative",
            "summary": "Convert\u0020an\u0020absolute\u0020url\u0020to\u0020a\u0020relative\u0020url.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#method_makeUrlRelative"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003AbuildUrlString\u0028\u0029",
            "name": "buildUrlString",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#method_buildUrlString"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UrlUtil\u003A\u003A\u0024requestStack",
            "name": "requestStack",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UrlUtil.html#property_requestStack"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil",
            "name": "UserUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "UserUtil\u0020constructor.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003AfindActiveUsersByGroup\u0028\u0029",
            "name": "findActiveUsersByGroup",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#method_findActiveUsersByGroup"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003AgetActiveGroups\u0028\u0029",
            "name": "getActiveGroups",
            "summary": "Returns\u0020all\u0020active\u0020users\u0020userGroups\u0020as\u0020a\u0020Collection\u0020of\u0020Models\u0020or\u0020null\u0020if\u0020user\u0020do\u0020not\u0020belong\u0020to\u0020any\u0020active\u0020userGroups",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#method_getActiveGroups"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003AhasActiveGroup\u0028\u0029",
            "name": "hasActiveGroup",
            "summary": "Returns\u0020true\u0020if\u0020the\u0020user\u0020or\u0020member\u0020\u0028frontend\u0020user\u0029\u0020is\u0020member\u0020of\u0020given\u0020group,\u0020false\u0020otherwise.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#method_hasActiveGroup"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003ATYPE_USER",
            "name": "TYPE_USER",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#constant_TYPE_USER"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003ATYPE_MEMBER",
            "name": "TYPE_MEMBER",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#constant_TYPE_MEMBER"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003A\u0024modelUtil",
            "name": "modelUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#property_modelUtil"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003A\u0024databaseUtil",
            "name": "databaseUtil",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#property_databaseUtil"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil\u003A\u003A\u0024contaoFramework",
            "name": "contaoFramework",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-UserUtil.html#property_contaoFramework"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils",
            "name": "Utils",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Utils\u0020constructor.",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method___construct"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Aaccordion\u0028\u0029",
            "name": "accordion",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_accordion"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Aanonymize\u0028\u0029",
            "name": "anonymize",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_anonymize"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Aarray\u0028\u0029",
            "name": "array",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_array"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Acontainer\u0028\u0029",
            "name": "container",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_container"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Adatabase\u0028\u0029",
            "name": "database",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_database"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Adca\u0028\u0029",
            "name": "dca",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_dca"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Afile\u0028\u0029",
            "name": "file",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_file"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Ahtml\u0028\u0029",
            "name": "html",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Alocale\u0028\u0029",
            "name": "locale",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_locale"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Amodel\u0028\u0029",
            "name": "model",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_model"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Arequest\u0028\u0029",
            "name": "request",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_request"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Arouting\u0028\u0029",
            "name": "routing",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_routing"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Astring\u0028\u0029",
            "name": "string",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_string"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Aurl\u0028\u0029",
            "name": "url",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_url"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003Auser\u0028\u0029",
            "name": "user",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_user"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003AgetSubscribedServices\u0028\u0029",
            "name": "getSubscribedServices",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#method_getSubscribedServices"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\Utils\u003A\u003A\u0024locator",
            "name": "locator",
            "summary": "",
            "url": "classes/HeimrichHannot-UtilsBundle-Util-Utils.html#property_locator"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Command",
            "name": "Command",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-command.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\ContaoManager",
            "name": "ContaoManager",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-contaomanager.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dca",
            "name": "Dca",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-dca.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Dom",
            "name": "Dom",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-dom.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EntityFinder",
            "name": "EntityFinder",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-entityfinder.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Event",
            "name": "Event",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-event.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\EventListener",
            "name": "EventListener",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-eventlistener.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-exception.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle",
            "name": "UtilsBundle",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle.html"
        },                {
            "fqsen": "\\HeimrichHannot",
            "name": "HeimrichHannot",
            "summary": "",
            "url": "namespaces/heimrichhannot.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Twig",
            "name": "Twig",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-twig.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util",
            "name": "Util",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-util.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\DcaUtil",
            "name": "DcaUtil",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-util-dcautil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\HtmlUtil",
            "name": "HtmlUtil",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-util-htmlutil.html"
        },                {
            "fqsen": "\\HeimrichHannot\\UtilsBundle\\Util\\UserUtil",
            "name": "UserUtil",
            "summary": "",
            "url": "namespaces/heimrichhannot-utilsbundle-util-userutil.html"
        }            ]
);
