services:
  huh.utils.listener.insert_tags:
    class: HeimrichHannot\UtilsBundle\EventListener\InsertTagsListener
    public: true
    autowire: true
  huh.utils.listener.frontend_page:
    class: HeimrichHannot\UtilsBundle\EventListener\FrontendPageListener
    public: true
    autowire: true
