services:
  _defaults:
    autowire: true
    bind:
      $bundleConfig: '%huh_utils%'

  HeimrichHannot\UtilsBundle\EventListener\:
    resource: '../../EventListener/*'
    public: true

  huh.utils.listener.insert_tags:
    class: HeimrichHannot\UtilsBundle\EventListener\InsertTagsListener
    public: true
  huh.utils.listener.frontend_page:
    class: HeimrichHannot\UtilsBundle\EventListener\FrontendPageListener
    public: true