services:
  _defaults:
    public: true
    autowire: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $webDir: '%contao.web_dir%'
      $utilsConfig: '%huh_utils%'

  huh.utils.accordion:
    class: HeimrichHannot\UtilsBundle\Accordion\AccordionUtil
  HeimrichHannot\UtilsBundle\Accordion\AccordionUtil: "@huh.utils.accordion"

  huh.utils.array:
    class: HeimrichHannot\UtilsBundle\Arrays\ArrayUtil
  HeimrichHannot\UtilsBundle\Arrays\ArrayUtil: "@huh.utils.array"

  huh.utils.cache.file:
    class: HeimrichHannot\UtilsBundle\Cache\FileCache
  HeimrichHannot\UtilsBundle\Cache\FileCache: "@huh.utils.cache.file"

  huh.utils.cache.remote_image_cache:
    class: HeimrichHannot\UtilsBundle\Cache\RemoteImageCache
  HeimrichHannot\UtilsBundle\Cache\RemoteImageCache: "@huh.utils.cache.remote_image_cache"

  huh.utils.class:
    class: HeimrichHannot\UtilsBundle\Classes\ClassUtil
  HeimrichHannot\UtilsBundle\Classes\ClassUtil: "@huh.utils.class"

  huh.utils.container:
    class: HeimrichHannot\UtilsBundle\Container\ContainerUtil
  HeimrichHannot\UtilsBundle\Container\ContainerUtil: "@huh.utils.container"

  huh.utils.date:
    class: HeimrichHannot\UtilsBundle\Date\DateUtil
  HeimrichHannot\UtilsBundle\Date\DateUtil: "@huh.utils.date"

  huh.utils.dca:
    class: HeimrichHannot\UtilsBundle\Dca\DcaUtil
  HeimrichHannot\UtilsBundle\Dca\DcaUtil: "@huh.utils.dca"

  huh.utils.file:
    class: HeimrichHannot\UtilsBundle\File\FileUtil
  HeimrichHannot\UtilsBundle\File\FileUtil: "@huh.utils.file"

  HeimrichHannot\UtilsBundle\File\FileArchiveUtil: ~
  huh.utils.file_archive: '@HeimrichHannot\UtilsBundle\File\FileArchiveUtil'

  HeimrichHannot\UtilsBundle\File\FolderUtil: ~
  huh.utils.folder: '@HeimrichHannot\UtilsBundle\File\FolderUtil'

  huh.utils.image:
    class: HeimrichHannot\UtilsBundle\Image\ImageUtil
  HeimrichHannot\UtilsBundle\Image\ImageUtil: "@huh.utils.image"

  huh.utils.model:
    class: HeimrichHannot\UtilsBundle\Model\ModelUtil
  HeimrichHannot\UtilsBundle\Model\ModelUtil: '@huh.utils.model'

  huh.utils.template:
    class: HeimrichHannot\UtilsBundle\Template\TemplateUtil
  HeimrichHannot\UtilsBundle\Template\TemplateUtil: "@huh.utils.template"