services:
  _instanceof:
    Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - ["setContainer", ["@service_container"]]

  HeimrichHannot\UtilsBundle\Util\Utils:
    public: true
    autowire: true
    autoconfigure: true

  HeimrichHannot\UtilsBundle\:
    resource: '../src/{Command,EntityFinder,EventListener,Util}/*'
    exclude: '../src/Util/Utils.php'
    autowire: true
    autoconfigure: true
    bind:
      $projectDir: '%kernel.project_dir%'
      $csrfTokenName: '%contao.csrf_token_name%'

  HeimrichHannot\UtilsBundle\Util\Container\ContainerUtil:
    autowire: true
    autoconfigure: true
    tags:
      - { name: 'container.service_subscriber', key: 'monolog.logger.contao', id: 'monolog.logger.contao' }